### ISSUE TITLE
both <UISref/> and stateService.go doesn't work properly with state definition

### ISSUE THREAD

**Issue by Hotell** [ui-router/react#11]
If I have following state definitions where children are defined with `parent`:

```typescript
const userListRouteConfig: ReactStateDeclaration = {
  name: 'users',
  url: '/',
  component: UsersPage
};

const userCreateRouteConfig: ReactStateDeclaration = {
  parent: 'users',
  name: 'new',
  url: '/new',
  component: UserCreatePage
};
```

and  UsersPage component with UISref or imperative injected router and relative reference to child:
```typescript
<MyButton 
  onClick={()=>this.props.transition.router.stateService.go('.new')}
>create new</MyButton>
<UISref to=".new">
  <button>create new</MyButton>
</UISref>
```

it doesn't transition to `new` route, even it doesn't throws any error.

this doesn't work as well:

```typescript
<UISref to="users.new">
  <button>create new</MyButton>
</UISref>
```

What works, is to explicitly define just the name, which is not very convenient for user, who is in the react component, because, he doesn't immediately know, that the create "new" is a child route
```typescript
<UISref to="new">
  <button>create new</MyButton>
</UISref>
```

**Comment by christopherthielen** [comment]
When estate is registered, the name provided is used as the basis for all lookups.  because of this, if you use the` parent:` notation, the parent state name is not part of the Child state name and therefore is not used during lookups.  

This is something I would consider changing in UI router core.  I think there is value in being able to address child states in this way.  I need to convince myself that there is no room for ambiguity, however, before this gets implemented.
