### ISSUE TITLE
Server-side rendering support

### ISSUE THREAD

**Issue by jonricaurte** [ui-router/react#15]
Server-side rendering support is a major feature to the react setup, so would be nice to have that, too.

**Comment by elboman** [comment]
We are working on it 😄  We have been talking about it internally and are trying to figure out a great and straightforward way to implement it.

Since the router is in charge of handling the resolves for each state, the best implementation would be to resolve the data on the server side, serialize it, send it to the client and re-hydrate the router state with the data, otherwise we would fetch all data twice.

This implementation has its limits as you would be able to only declare resolves that can be serialized. So no class instances or stuff like that.

I'll update here as soon as we have anything working ;)

**Comment by jonricaurte** [comment]
Glad to hear!

This is the library I'm currently using with react-router:

https://github.com/makeomatic/redux-connect
API: https://github.com/makeomatic/redux-connect/blob/master/docs/API.MD

Using both redux and react-router along with redux-connect is a solution working for me for both client and server. Maybe have something similar, or maybe letting the router have plugins for specific kinds of stores like redux. The other one I was looking at was react-resolver, but it doesn't support redux out of the box:

https://github.com/ericclemmons/react-resolver

The only thing without using classes is you would have to have a nested component at the top level if you wanted to setState. Maybe that could be fine if it is just documented well. Decorators as resolvers makes it easy to see whats being injected into the props of the component but not necessarily required. Really like what you guys are doing! Miss ui-router to be honest.

This is the boilerplate I started with for my app which emphasizes the folder by feature/routes are folders (called fractal pattern in React but has been around for a while in Angular community thanks to John Papa):

https://github.com/davezuko/react-redux-starter-kit

Any kind of time frame you guys are looking at for a 1.0?

**Comment by lfender6445** [comment]
Any updates on this?

**Comment by elboman** [comment]
I have to be honest, I haven't work specifically on this feature, but we have made big changes since that should render this a lot easier to implement.
I guess it's time for me to work on it properly.

I'll keep you posted!
