### ISSUE TITLE
Code Splitting

### ISSUE THREAD

**Issue by codepunkt** [ui-router/react#19]
Is there a way to use route-based code splitting with ui-router/react?

**Comment by elboman** [comment]
Sure! UI-Router Core 1.0 introduced future states and lets you lazy load them when needed.
All you need to do is declare the future state:

```jsx
{
  name: 'lazy',
  url: '/this-is-lazy',
  lazyLoad: () => System.import('./lazyLoadState')
}
```

The `lazyLoadState` file must declare the state **that will replace with the future-state** (that acts as a placeholder) and export a default object with a `states` attribute.

```jsx
import MyComponent from './MyComponent';
const state = {
  name: 'lazy',
  url: '/this-is-lazy',
  component: MyComponent
};
export default { states: [state] }
```

Note that the syntax for lazy loading a JS module depends on the bundler you use. Since the `lazyLoad` function in your state declaration requires you to return a promise, verbosity may change drastically based on your module bundler: Webpack 2 supports `System.import()` as well as `import()`, while webpack 1.x supports the verbose `require.ensure()` syntax which isn't promise-based.

This doesn't prevent you from writing a small helper function to reduce this verbosity:
```jsx
const lazyLoadModule = (moduleName) => new Promise((resolve, reject) => {
  require.ensure([], () => { resolve(require(moduleName).default) });
});

const state = {
  name: 'lazy',
  url: '/this-is-lazy',
  lazyLoad: () => lazyLoadModule('./lazyLoadState')
}
```

In any case I wrote a small working example, hope it helps: http://www.webpackbin.com/Ekiu1rHNz

Also, you can take a look at the core documentation regarding future states here: https://ui-router.github.io/docs/latest/interfaces/state.statedeclaration.html#lazyload

Let me know if you have any doubt

**Comment by MichaelBuen** [comment]
http://www.webpackbin.com/Ekiu1rHNz link is no longer working

![image](https://user-images.githubusercontent.com/1811636/27250215-3c8363ea-535b-11e7-9cc3-a6f00fa1d3dd.png)

I tried the code-splitting with @uirouter/react. The chunk is loading in network tab, however for some reason the component is not rendering in the page. @uirouter/react works with if there's no code-splitting. if I put the component directly on state's component property. Is there any plugins that I missed or something?

**Comment by MichaelBuen** [comment]
I'm thinking the code-splitting's problem is caused by using `module: commonjs` in tsconfig.json, however if I set it to `umd`, typescript complains:

![image](https://user-images.githubusercontent.com/1811636/27250365-4ad6ecbe-5360-11e7-912e-3128a6924d7e.png)

Is there a plunker or webpackbin example with code-splitting usage, and also with `otherwise`?

I have good experience with `ui-router` in Angular 1.x and lazy-loading with it using `ocLazyLoad`. I'm thinking if I can use `@uirouter/react` with lazy-loading despite being 0.5.0 version.

**Comment by brendanmckeown** [comment]
@MichaelBuen and for anyone else who stumbles upon this issue, I fixed this by exporting a `states` array from the lazy-loaded module, instead of exporting the default.
```
const state = {
    name: 'home',
    url: '/home',
    component: App
};

export const states = [state];
```
