### ISSUE TITLE
How to set root state for nested routes

### ISSUE THREAD

**Issue by mbrimmer83** [ui-router/react#202]
I am trying to move my react application to ui-router/react and have an App component that wraps each view in the application.
```
export default [{
  path: '/',
  component: App,
  routes: [
    {
      path: '/',
      name: HOME_PAGE,
      component: Home,
    },
    {
      path: '/error',
      name: ERROR_PAGE,
      component: NotFound,
    }
  ]
}] // React-router config - what I want to do, but with ui-router/react
```

```
export default [
  {
    name: 'app',
    url: '/',
    component: App,
  },
  {
    name: 'app.home',
    url: '/',
    component: Home,
  },
  {
    name: 'app.error',
    url: '/error',
    component: NotFound,
  },
]
// Renders the App component without the Home component.
```
Is it possible to have this type of root component where every view is rendered as a child of the root component in ui-router/react? This is not an issue but I wasn't able to find a place to submit questions. I am used to react-router and new to ui-router. Thanks for any help!

**Comment by elboman** [comment]
Hi there! Yeah you can definitely do this, as you can nest as many `UIView` as you want. Child views will be rendered in the nested view and so on.

So a basic code example would be:
```
// main app component
const Main = () =>
	<div className="or-wahtever-dom-you-need"><UIView /></div>;

ReactDOM.render(<Main />, document.getElementById('root'));
```

```
// your routed App component
const App = () =>
	<div className="some-class-name">
		<p>some markup I need in App (for example as template)</p>
		<UIView />
	</div>
```

This way `App` will be rendered in the main `UIView` as it's a root state (doesn't have any parent state), and its children will be rendered in its `UIView`.

You can even have more than one `UIView` per component, but if you do this, you need to name them otherwise it wouldn't know in which view it should render the component.

Hope this helps!

**Comment by mbrimmer83** [comment]
@elboman Yes, this does help. Thanks for the quick reply.
