### ISSUE TITLE
router.urlRouter.otherwise(…) doesn't work with pushStateLocationPlugin

### ISSUE THREAD

**Issue by martin-kral** [ui-router/react#21]
Hi Marco,
first of all thank you for your work on UI Router framework.

I have two issues with new version (0.4.0) of React UI Router. Both are connected with `config` prop of `UIRouter` component:

1. First - there is a wrong `config` prop [example](https://github.com/ui-router/react/blob/master/docs/API.md#uirouter) using the old router.**urlRouterProvider**.otherwise (I think it should be router.**urlRouter**.otherwise(…)).
2. Second - `otherwise` setting through `config` prop works only with **hashLocationPlugin** for me. It doesn’t work with the recommended **pushStateLocationPlugin** plugin. This plugin redirects the app to the desired url, but nothing else happens. BUT it works correct when I set `otherwise` through manual bootstraping, i.e.:
```
const router = new UIRouterReact()
...
router.urlRouter.otherwise("/client/list")
...
router.start()
```

**Comment by elboman** [comment]
Hi Martin!

Thanks for trying out the new version and provide feedbacks 😄 

You're right, `urlRouterProvider` is deprecated in favor of `urlRouter`, I will update the example asap!

The second issue is related to a bug in `ui-router-core` (ui-router/core#23) and should be fixed in the next version.

If you still want to use the `config` prop, the otherwise rule should work when using a state name instead of an url:
```jsx
router.urlRouter.otherwise({ state: 'yourstatename' })
```

**Comment by martin-kral** [comment]
Hi Marco,
good recommendation - using state name instead of url works prefect (and moreover cleaner solution then hardcoded url).
Thank you very much for quick response.
