### ISSUE TITLE
UIView Pass Props & Propogate Changes To Children

### ISSUE THREAD

**Issue by Schlesiger** [ui-router/react#26]
Greetings,

It doesn't seem that props from UIView are passed on to the children except for a select few. Furthermore, the props that are passed are never updated in the children of UIView after they change. I request that properties propogate from UIView into their children and those children receive updates.

I am trying to create a reusable component that prepopulates ui-router states. For example, given an array of tabs and an array of drawers, generate the routes, views, with relative and absolute naming. This component would be an easy starting point for new users to ui-router and enable early complex routing.

Currently this is working but the component requires context and a state manager like Redux to get props to children of UIView and have changes propagate. For the component to be reusable, it'd be best if a state manager wasn't included and React component state was used instead.

I tried using context alone but [context changes don't propogate](https://github.com/facebook/react/issues/2517). I am going to play with using callbacks in my context instead, but the cleaner and easier solution would be if UIView passed props and propogated changes to child components.

Thanks.

**Comment by elboman** [comment]
Hi,
You're right, currently UIView only injects a handful of props:
```ts
export interface InjectedProps {
  transition?: Transition,
  resolves?: Resolves,
  className?:string,
  style?: Object
}
```

I understand your need and I would like to find a solution that can be useful for other situations as well. 

Instead of passing down all the props (which is not a good practice for a number of reasons), I think the best solution here would be something as mentioned here (#13):

```jsx
<UIView render={(Component, props) =>
  <Component {...props} />
} />
```
where `Component` is the component class you passed in the state declaration and props are the four props above. You can then append your own like this:

```jsx
<UIView render={(Component, props) =>
  <Component {...props} {...someOtherProps} />
} />
```

This way you should be able to achieve what you a looking for (and actually a lot more). What do you think? Do you see any problem with this implementation? We have been discussing it a bit and I'd like to release it in the next version.

**Comment by Schlesiger** [comment]
I like that a lot. Changes should also propagate easily. Thanks, I really look forward to trying it!

**Comment by Schlesiger** [comment]
I was thinking about this some more; what about views? I currently have parallel views in multiple state definitions. The component in a named UIView can change given the state.

**Comment by cef62** [comment]
@elboman there are plans on when the next release will be released? We are using `ui-router` in a big react application and I'm trying to figure out how to manage visual animation on router transitions.

Thanks!
