### ISSUE TITLE
Webpack compilation issues?

### ISSUE THREAD

**Issue by JMStudiosJoe** [ui-router/react#29]
I have been trying to use ui-router-react but can not get past webpack complaints for some reason.
ERROR in [at-loader] node_modules/ui-router-core/lib/common/common.d.ts:388:31
    TS7006: Parameter 'a' implicitly has an 'any' type.

ERROR in [at-loader] node_modules/ui-router-core/lib/common/common.d.ts:388:34
    TS7006: Parameter 'b' implicitly has an 'any' type.

ERROR in [at-loader] node_modules/ui-router-core/lib/resolve/resolveContext.d.ts:7:22
    TS7005: Variable 'NATIVE_INJECTOR_TOKEN' implicitly has an 'any' type.

ERROR in [at-loader] node_modules/ui-router-core/lib/transition/transitionHook.d.ts:13:37
    TS7006: Parameter 'error' implicitly has an 'any' type.

ERROR in [at-loader] src/components/loginComponent.tsx:23:33
    TS2314: Generic type 'KeyboardEvent<T>' requires 1 type argument(s).

ERROR in [at-loader] src/components/loginComponent.tsx:32:31
    TS2314: Generic type 'KeyboardEvent<T>' requires 1 type argument(s).

These errors (besides last two) only happen when I try to import  
import {UIRouter, UIView, UISref, UISrefActive, pushStateLocationPlugin} from 'ui-router-react';

here is link to the project under branch reactRouting: https://github.com/JMStudiosJoe/ReactPractice/tree/reactRouting
any advice and help would be great, thank you in advance I hope this is just a small stupid step I missed cause this is frustrating.

**Comment by warrenseymour** [comment]
@JMStudiosJoe There may be a better solution that this (the best being to fix the implicit any types in the core) , adding `"skipLibCheck": true` to your project's `tsconfig.json` should suppress these errors.

**Comment by elboman** [comment]
So, I took a look at the code. The problem here is the fact that the `ui-router-core` lib is developed with the `noImplicitAny` default value, which is `false`, while your config sets it to `true`. This is why the core lib compiles fine in the source but doesn't in your setup.

That being said, you can fix the problem (for now) by setting `"noImplicitAny": false` in your `tsconfig.json` and let TS deal with implicit `any` types, unless you prefer skipping the whole lib check and in that case you can do what @warrenseymour suggests. 

I guess the core lib should support your configuration and we should make a PR to explicitly set the `any` type on those variables.

**Comment by JMStudiosJoe** [comment]
@warrenseymour and @elboman thank you both for fast responses and both solutions worked to let you know.
