### ISSUE TITLE
ui-router-react fails with Rollup

### ISSUE THREAD

**Issue by mfreeman-xtivia** [ui-router/react#33]
When attempting to bundle a React app that uses ui-router-react I get a zillion complaints from Rollup along the lines of 

Error: Cannot call a namespace ('classNames')

Based on similar errors I see documented for Rollup...

```
When importing a module's namespace using * as foo you get a namespace object which isn't callable. You should import default export instead. 

import express from 'express';

const app = express();
```

**Comment by elboman** [comment]
Hi,
I haven't tried Rollup yet, but it looks like it doesn't like the `import * as something from 'something'` syntax.

Unfortunately the only way to fix it is to change the way we import `classnames` in the library (which will be addressed in next release), unless you are using typescript in you application. In that case you simply need to add synthetic default imports in your `tsconfig.json`:

```
"allowSyntheticDefaultImports": true,
```

Sorry for the inconvenience

**Comment by christopherthielen** [comment]
Interesting.  [We're using Rollup to bundle angular-ui-router](https://github.com/angular-ui/ui-router/blob/master/rollup.config.js) which should be nearly the same, right?

**Comment by mfreeman-xtivia** [comment]
Don't know as I am not using that one at the moment---I did have success using Rollup to bundle ui-router for angular 2, both for JIT and AOT mode. But no joy for the React version and Rollup.

**Comment by christopherthielen** [comment]
Tried bundling ui-router-react, got the error:

```
(79): lib-esm/reactViews.js🚨   Cannot call a namespace ('classNames')
lib-esm/components/UISref.js (49:23)
47:             onClick: this.handleClick,
48:             href: this.context['router'].stateService.href(to, params, options),
49:             className: classNames(this.props.className, childrenProps.className)
                           ^
50:         });
51:         return cloneElement(this.props.children, props);
```

**Comment by christopherthielen** [comment]
@elboman See #34

**Comment by christopherthielen** [comment]
Here's an issue reported for "classnames" + typescript + synthetic default + webpack

https://github.com/Microsoft/TypeScript/issues/7518#issue-140962151

**Comment by elboman** [comment]
So, I'm trying to find out the problem.

It looks like TS wants the `import * as X from Y` syntax to handle modules which don't have a default import. I never used this syntax before using typescript (unless I wanted to include all exports in a single object) because babel changes the way default export are transpiled (https://github.com/Microsoft/TypeScript/issues/11057).

On the other hand, rollup doesn't like that syntax (as pointed out here https://github.com/rollup/rollup/issues/670) hence the problem. 

A solution would probably be to add babel and let it transpile the export in the modules, but I don't like it as we don't need babel.

I guess the "magic" solution works for now, and we'll change it accordingly once we'll find a better solution.
