### ISSUE TITLE
Deprecated Warning about PropTypes

### ISSUE THREAD

**Issue by iamashraful** [ui-router/react#48]
Console says - 
`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

I guess this is for defining const in index.js (root) file. Can you please help me get out from here?

**Comment by kaumac** [comment]
I tried to fix this one, but without knowing which components are causing this I got lost.

I'm pretty sure this happens because on ui-router-react components, the proptypes are being defined like this:
```
import React from 'react';
const PropTypes = React.propTypes;
UISref.propTypes = {
	someProp: PropTypes.string,
	otherProp: PropTypes.bool
};
```

Not necessarily like this, but in a sense that the propTypes are being imported directly from the 'react' package, and as of React 15.5.x doing this will throw deprecation errors as there is a package just for this ([https://www.npmjs.com/package/prop-types](https://www.npmjs.com/package/prop-types))

So it's not a problem on your code, we just need to update this on ui-router-react

**Comment by kaumac** [comment]
#46 Seems to address the problem

**Comment by iamashraful** [comment]
@kaumac Thanks for nicely explaining. So, I should wait for `ui-router-react` update.

**Comment by elboman** [comment]
Yeah, sorry if I didn't update you back, but `0.5.0` version of `@uirouter/react` solves this warning.
