### ISSUE TITLE
Is this project still under active development?

### ISSUE THREAD

**Issue by matei-radu** [ui-router/react#504]
Non-technical question here.

I'm evaluating the use of _UI-Router for React_ within my company as an alternative to the troublesome _React Router_ package.

My initial impressions are very positive and I'm strongly inclined to migrate to your package. However, I noticed that both this and the core package have made no releases since January 2019 and most of the PRs are from a dependency bot.

#### Is UI-Router still under active development?
If it still is, I'm more than willing to contribute to the project if my company ends up adopting it, althought it would be more on the React-specific package since that is my area of expertise.

**Comment by christopherthielen** [comment]
Hi, I'm the primary maintainer of the ui-router suite of packages.  I am not personally actively developing new features these days.  I am trying to keep the packages up to date and also squash as many bugs as possible  (major or minor).  

We use the `@uirouter/react-hybrid` package on my project at Netflix, so I am personally motivated to continue to invest at least _some_ time into the project.  If you (or anyone else) wants to contribute towards the project (features, or otherwise), I'm very motivated to provide significant guidance and help.

**Comment by matei-radu** [comment]
Thanks for clearing this.

I'll let you know by the end of the week if we'll settle with ui-router or not. If we do, we can then see how we can start contributing to the package :)

**Comment by matei-radu** [comment]
It took longer than anticipated, sorry.

Ultimately we agreed to continue with our existing setup so we will not adopt UI-Router.
