### ISSUE TITLE
Simplify/merge `UISref` and `UISrefActive`

### ISSUE THREAD

**Issue by Kukkimonsuta** [ui-router/react#57]
I believe the current syntax is too verbose for common cases, so I'd like to propose either adding alternative API or merging both into single component.

Standard case:
```tsx
<UISrefActive class="active"><UISref to="messages"><a>Messages</a></UISref></UISrefActive>
```

```tsx
<UISref to="messages" activeClassName="active">Messages</UISref>
```

Custom component:
```tsx
<UISrefActive class="active"><UISref to="messages"><button>Messages</button></UISref></UISrefActive>
```

```tsx
<UISref to="messages" activeClassName="active" component="button">Messages</UISref>
```

**Comment by elboman** [comment]
I understand your point, but there are a couple of reasons why we went with this setup:

* maintain consistency between UI Router framework implementations
* give a flexible way to handle complex DOM structures

There are cases where you don't want the `active` class to be attached to the `UISref` component because of some tricky DOM structure in your menus:

```jsx
<UISrefActive class="active">
  <li className="some-menu">
    <!-- might need some nodes here -->
    <UISref to="somewhere">
      <a>Some link</a>
    </UISref>
  </li>
</UISrefActive>
```

I understand your concern with verbosity but you can always take advantage of React components to take care of that:

```jsx
const Link = ({ to, activeClassName, children }) =>
  <UISrefActive class={activeClassName}>
    <UISref to={to}>{children}</UISref>
  </UISrefActive>;

// ...

<Link to="somestate" activeClassName="active"><button>Some link</button></Link>
```

or even:

```jsx
import React, {createElement} from 'react';

const Link = ({ to, activeClassName, element, children }) =>
  <UISrefActive class={activeClassName}>
    <UISref to={to}>{createElement(element, {}, children)}</UISref>
  </UISrefActive>;

// ...

<Link to="somestate" activeClassName="active" element="button">Some link</Link>
```

**Comment by Kukkimonsuta** [comment]
That makes sense, however I still think there should be less verbose way to do this. What about just adding optional `activeClassName` to `UISref` and let user decide whether can use shorter syntax or whether `UISrefActive` is required? It feels weird having two ways to do the same thing, but I believe out of the box simplicity is worth it.

Components are fun and do solve the problem if you have a lot of `UISref`s with active class name, but you either have to create new for every file or have yet another imported file - which introduces verbosity by itself.

**Comment by eddiemonge** [comment]
> have yet another imported file

Composing the two together like in @elboman's example would actually cut down on imports. Instead of `import {UISrefActive, UISref} from '@uirouter/react'`, it would become `import Link from './my-components`.

> adding optional activeClassName to UIS

This would make the library more complex. Adds more code and logic and also makes implementation more complex. What happens when a user has both UISrefActive and adds the optional activeClassName?

Marking this as closed since it is both old and alternate solutions have been presented.
