### ISSUE TITLE
How to go back to previous visited route programmatically?

### ISSUE THREAD

**Issue by yofret** [ui-router/react#61]
I have reading the Docs on how to go back to previous State/page visited, but I don't find anything in the docs, please if you could point me the right direction that would be great

Thanks! and awesome work!

**Comment by elboman** [comment]
The best thing would be to get the previous state from the last transition and use that as target:

Inside a routed component you can access the transition via props:

```jsx
  render () {
    let {transition} = this.props;

    // access the state we navigated from
    let prevState = transition.from();
    let prevParams = transition.params('from');

    // navigate to the state
    transition.router.stateService.go(prevState, prevParams);
  }
```

Since the router is synced with the browser history you can always navigate back using the DOM api:

```jsx
window.history.back();
```

I guess it depends on what you need to achieve.

The first method is useful for handling redirects inside the application. In the sample app we redirect users that are not logged in to the log in page. Once the user has logged we find out which state triggered the original redirect and redirect the user back to that state (you can [see here](https://github.com/ui-router/sample-app-react/blob/master/src/main/states.js#L65) what I'm trying to explain).

Glad to help! Let me know if you have any more doubts!

**Comment by MarcoPortillo** [comment]
@elboman Hi, thanks for the explanation.

It didn't work for me, nothing happens if I apply this. Using the DOM api is not an option for me, aren't there any other ways to go back? The documentation says nothing about it.

**Comment by yofret** [comment]
Oh Wow, I never replied to this thread, It did work for me when I was using it! I never gave a proper thanks!
