### ISSUE TITLE
Suggestion: Throw error if user calls UIRouterReact.start() twice

### ISSUE THREAD

**Issue by telekid** [ui-router/react#65]
I burned a few hours attempting to fix an issue that was actually a side-effect of unintentionally calling `start()` on my `router` object twice – once in my `router.config` file (inspired by [the sample app](https://github.com/ui-router/sample-app-react/blob/master/src/router.config.js#L24),) and then once again by passing `router` to the `UIRouter` component.

The trouble is, it isn't particularly obvious that passing a `UIRouterReact` class to a `UIRouter` component (`<UIRouter router={router}></UIRouter>`) automatically calls the `start()` method on `router`.

Since I can't actually think of any reason why a user _would_ choose to call `router.start()` twice in the same application, it may be prudent to throw an error if a user attempts to do so.

**Comment by elboman** [comment]
Yeah, we should definitely warn the user if the `start` method is called more than once.

The thing is, since the `UIRouter` component takes care of `start()`ing the router whether you pass it an instance or let it create the instance for you, I don't think you ever need to do it yourself.

We should definitely update the sample app (as it's using the old version/syntax) as well as migration guide from the 0.4.x

Thanks for the heads up!
